baseURL = "http://theochem.chem.okayama-u.ac.jp/"
languageCode = "ja-JP"
title = "理論化学研究室"
# theme = "hugo-arcana"
theme = "tetrahedroid.github.io"
copyright = "© Theoretical Chemistry Lab. All rights reserved"

defaultContentLanguage = "ja"
[languages]
    [languages.ja]
        languageName = "日本"
        weight = 1
    [languages.en]
        languageName = "English"
        weight = 2
    # [languages.de]
    #     languageName = "Deutsch"
    #     weight = 3

[taxonomies]
    tag = "tags"
    # これを処理する場所は?

[params]
    description = "理論化学研究室"
    show_post_dates = true

    # [[params.social]]
    #     title = "Twitter"
    #     icon = "fa-twitter"
    #     url = "#"
    # [[params.social]]
    #     title = "Facebook"
    #     icon = "fa-facebook-f"
    #     url = "#"
    [[params.social]]
        title = "GitHub"
        icon = "fa-github"
        url = "https://github.com/tetrahedroid/"
    # [[params.social]]
    #     title = "LinkedIn"
    #     icon = "fa-linkedin-in"
    #     url = "#"
    [[params.social]]
        title = "Creative Commons"
        icon = "fa-creative-commons"
        url = "https://creativecommons.org/"


    [params.footer]
        [[params.footer.links]]
            header = "理論化学研究室"
        [[params.footer.links.links]]
            title = "ホーム"
            url = "/"
        [[params.footer.links.links]]
            title = "最新情報"
            url = "/posts"
        [[params.footer.links.links]]
            title = "研究"
            url = "/research"
        [[params.footer.links.links]]
            title = "メンバー"
            url = "/members"


        [[params.footer.links]]
            header = "リンク"
        [[params.footer.links.links]]
            title = "理学部化学科"
            url = "http://www.chem.okayama-u.ac.jp"
        [[params.footer.links.links]]
            title = "理学部"
            url = "http://www.science.okayama-u.ac.jp"
        [[params.footer.links.links]]
            title = "異分野基礎科学研究所"
            url = "http://www.riis.okayama-u.ac.jp"
        [[params.footer.links.links]]
            title = "環境生命自然科学研究科"
            url = "http://www.gnst.okayama-u.ac.jp"
        [[params.footer.links.links]]
            title = "岡山大学"
            url = "http://www.okayama-u.ac.jp"

        # [[params.footer.links]]
        #     header = "More Links to Stuff"
        # [[params.footer.links.links]]
        #     title = "Duis neque nisi dapibus"
        #     url = "#"
        # [[params.footer.links.links]]
        #     title = "Sed et dapibus quis"
        #     url = "#"
        # [[params.footer.links.links]]
        #     title = "Rutrum accumsan sed"
        #     url = "#"
        # [[params.footer.links.links]]
        #     title = "Mattis et sed accumsan"
        #     url = "#"
        # [[params.footer.links.links]]
        #     title = "Duis neque nisi sed"
        #     url = "#"
        # [[params.footer.links.links]]
        #     title = "Sed et dapibus quis"
        #     url = "#"
        # [[params.footer.links.links]]
        #     title = "Rutrum amet varius"
        #     url = "#"

        [params.footer.contact_form]
            enabled = false
            header = "Get In Touch"
            action = ""
