[params]
    description = "A business/corporate style responsive site template."
    show_post_dates = false

    # [[params.social]]
    #     title = "Twitter"
    #     icon = "fa-twitter"
    #     url = "#"
    # [[params.social]]
    #     title = "Facebook"
    #     icon = "fa-facebook-f"
    #     url = "#"
    [[params.social]]
        title = "GitHub"
        icon = "fa-github"
        url = "https://github.com/tetrahedroid/"
    # [[params.social]]
    #     title = "LinkedIn"
    #     icon = "fa-linkedin-in"
    #     url = "#"
    [[params.social]]
        title = "Creative Commons"
        icon = "fa-creative-commons"
        url = "https://creativecommons.org/"


    [params.footer]

        [[params.footer.links]]
            header = "Theoretical Chemistry Laboratory"
        [[params.footer.links.links]]
            title = "Home"
            url = "/en"
        [[params.footer.links.links]]
            title = "Posts"
            url = "/en/posts"
        [[params.footer.links.links]]
            title = "Research"
            url = "/en/research"
        [[params.footer.links.links]]
            title = "Members"
            url = "/en/members"


        [[params.footer.links]]
            header = "Links"
        [[params.footer.links.links]]
            title = "Dept. of Chemistry"
            url = "http://www.chem.okayama-u.ac.jp/en"
        [[params.footer.links.links]]
            title = "Faculty of Science"
            url = "http://www.science.okayama-u.ac.jp/en"
        [[params.footer.links.links]]
            title = "Research Institute for Interdisciplinary Science"
            url = "http://www.riis.okayama-u.ac.jp/m"
        [[params.footer.links.links]]
            title = "Graduate School for Natural Sci. and Tech."
            url = "http://www.gnst.okayama-u.ac.jp/e"
        [[params.footer.links.links]]
            title = "Okayama University"
            url = "http://www.okayama-u.ac.jp/index_e.html"

        # [[params.footer.links]]
        #     header = "More Links to Stuff"
        # [[params.footer.links.links]]
        #     title = "Duis neque nisi dapibus"
        #     url = "#"
        # [[params.footer.links.links]]
        #     title = "Sed et dapibus quis"
        #     url = "#"
        # [[params.footer.links.links]]
        #     title = "Rutrum accumsan sed"
        #     url = "#"
        # [[params.footer.links.links]]
        #     title = "Mattis et sed accumsan"
        #     url = "#"
        # [[params.footer.links.links]]
        #     title = "Duis neque nisi sed"
        #     url = "#"
        # [[params.footer.links.links]]
        #     title = "Sed et dapibus quis"
        #     url = "#"
        # [[params.footer.links.links]]
        #     title = "Rutrum amet varius"
        #     url = "#"

        [params.footer.contact_form]
            enabled = false
            header = "Get In Touch"
            action = ""
